### ISSUE TITLE
Definition differences between python and C

### ISSUE THREAD

**Issue by fpietka** [tebeka/fastavro#102]
I have a strange error using C compiled fastavro, calling `schemaless_reader()`

```
Traceback (most recent call last):
  File "/home/fpietka/.pyenv/versions/fpietka/lib/python3.6/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 173, in _get_decoder_func
    schemaless_reader(payload, schema_dict)
  File "/home/fpietka/.pyenv/versions/fpietka/lib/python3.6/site-packages/fastavro/reader.py", line 606, in schemaless_reader
    acquaint_schema(schema, READERS)
TypeError: _acquaint_schema() takes 1 positional argument but 2 were given
```

And when I output the definition I have this:
```python
def _acquaint_schema(schema):
    """Add a new schema to the schema repo.

    Parameters
    ----------
    schema: dict
        Schema to add to repo
    """
    _reader.acquaint_schema(schema)
    _writer.acquaint_schema(schema)
```

Seems the difference is here:
https://github.com/tebeka/fastavro/blob/e752a9559368ea2d12d17f33263a2c80e8c9409f/fastavro/__init__.py#L60-L69

Following up on https://github.com/tebeka/fastavro/issues/101 what do you suggest me to do?

Thanks

**Comment by fpietka** [comment]
Ok, I just used the other method you suggested:
```python
from fastavro.reader import read_data, READERS
from fastavro.schema import acquaint_schema
```

Using `schemaless_reader()` doesn't work, I have to call explicitly `acquaint_schema()` from `schema` (this one works), then `read_data()`.

Guess I'll have to update my PR on confluent-kafka. What do you think?

**Comment by scottbelden** [comment]
I'm looking into this. I think I might have a solution.

**Comment by scottbelden** [comment]
@fpietka I was able to see the same behavior as you when doing `from fastavro.reader import schemaless_reader` but if I do `from fastavro import schemaless_reader` then it works. This feels ugly to me and in general there is some ugliness related to the `__init__.py` as mentioned here: https://github.com/tebeka/fastavro/issues/36.

Can you try `from fastavro import schemaless_reader` and let me know if that works for you?

**Comment by fpietka** [comment]
It works, and also seems a bit faster when I bench it.

**Comment by scottbelden** [comment]
Great. I'm going to close this. If there is still something unanswered please re-open.
