### ISSUE TITLE
Add support for fixed type for logicalType decimals

### ISSUE THREAD

**Issue by glgnohk** [tebeka/fastavro#105]
I.e.: 
```
  "type": 
    {
        "name": "MyFixedDecimal",
        "type": "fixed",
        "size": 8,
        "logicalType": "decimal",
        "precision": 18,
        "scale": 6
    },
```

I think what has to be done:

### Add "fixed-decimal" to LOGICAL_READERS and LOGICAL_WRITERS
"bytes-decimal" is in both of these, but not "fixed-decimal"

### Add functions to the above
For the reader, function ```read_bytes_decimal``` should be able to handle the fixed-decimals, as it does ```size = len(data)```.

For the writer, will need to make a new function. Can take from https://github.com/apache/avro/pull/82/, like the current code.

### Add "fixed-decimal" to validate
Add:
```
if record_type == 'fixed':
        return (
            (isinstance(datum, bytes) and len(datum) == schema['size'])
            or (isinstance(datum, decimal.Decimal))
        )
```

Union calls validate, so you'll need this if use union with "fixed-decimal".

**You could monkey patch the reader with:**
```
fastavro._reader.LOGICAL_READERS['fixed-decimal']=fastavro._reader.LOGICAL_READERS['bytes-decimal']
```

I could attempt a PR.

**Comment by scottbelden** [comment]
This sounds like it shouldn't be too hard to implement. Feel free to submit a PR. Thanks!

**Comment by scottbelden** [comment]
resolved via https://github.com/tebeka/fastavro/pull/106
