### ISSUE TITLE
Drop support for python 2.6?

### ISSUE THREAD

**Issue by scottbelden** [tebeka/fastavro#107]
2.6 has been end of life for over 4 years now. I noticed there's a few places where special handling is done to support 2.6 that could be simplified by removing that support.

Thoughts @tebeka?

**Comment by tebeka** [comment]
I kept 2.6 support around since it was the version on CentOS where most Hadoop installations were on. However it's been a while and I'm not that informed. If you think it's not out there anymore - we can probably drop it.

**Comment by scottbelden** [comment]
I just downloaded a CentOS 7 image and it has 2.7.5 as the default python install.

**Comment by tebeka** [comment]
IIRC these were CentOS 5 or 6. Looks like CentOS 6 stopped getting full updates on May this year (and is about 6 years old). I'm OK with dropping 2.6 support.
