### ISSUE TITLE
disable logical type conversion how?

### ISSUE THREAD

**Issue by costa** [tebeka/fastavro#116]
I wonder if I can prevent conversion of `{"type": "long", "logicalType": "timestamp-millis"}` into the wondrous `datetime` (https://stackoverflow.com/questions/6999726/how-can-i-convert-a-datetime-object-to-milliseconds-since-epoch-unix-time-in-p).
Thanks in advance you brave people writing in Python.

**Comment by kkirsanov** [comment]
```
import fastavro
fastavro._reader.LOGICAL_READERS['long-timestamp-millis'] = lambda x:x
```

**Comment by costa** [comment]
Nope, this doesn't work, neither with 'timestamp-millis' nor with 'long-timestamp-millis'.

**Comment by kkirsanov** [comment]
sorry
```
lambda x:x
=>
lambda d, w, r: d
```

https://gist.github.com/kkirsanov/d64a3c2899675e8aa35870c608fe7e12

**Comment by scottbelden** [comment]
Closing this. Feel free to re-open if you are still having trouble.

**Comment by costa** [comment]
FYI, the "solution" has stopped working with the current version (I think I'm at 0.17.10), `s/reader/read/` above.
A README note or something will be appreciated, I'm sure.

A solution with less monkey-patching will be even more welcome. Thanks.

**Comment by costa** [comment]
@scottbelden Re: logical type removal: thanks, this is even less a solution, since I'm having problem just with the python component, all others are fine and enjoying the logical types, thanks again.

Now I don't think I have any direct business with `fastavro`, and I'd also like to stay at the `confluent_kafka` API level.

What I do is:
```python
...
from confluent_kafka import avro
...
    value_schema = avro.load(KAFKA_EMIT_TOPIC+'-value.avsc')
...

    producer = AvroProducer({'bootstrap.servers': KAFKA_BOOTSTRAP_SERVERS, 'schema.registry.url': KAFKA_REGISTRY_URI},
                            default_value_schema=value_schema)

    consumer = AvroConsumer({'bootstrap.servers': KAFKA_BOOTSTRAP_SERVERS, 'group.id': KAFKA_INGEST_GROUP, 'schema.registry.url': KAFKA_REGISTRY_URI})
    consumer.subscribe([KAFKA_INGEST_TOPIC])
...
            msg = consumer.poll(KAFKA_POLL_SEC)
...
```
Then I use `msg.value()` which has my (`long`) `ts` converted to `datetime`.
To me, the perfect solution would be giving some options to `AvroConsumer` (e.g. `AvroConsumer({..., 'schema.logical.type': {'ts': None}})` or `AvroConsumer({..., 'schema': <specially-augmented-avsc>})`)

**Comment by scottbelden** [comment]
@costa For the `confluent_kafka` level you would probably need to create an issue or PR for them. However, I think they would still need a change from us so that they could set the `use_logical_types` to `False`.

**Comment by scottbelden** [comment]
@costa @kkirsanov I took a stab at this. The changes are in https://github.com/tebeka/fastavro/pull/186.

You can see how this works from the test, but essentially you just use the argument `use_logical_types=False` when using the `reader` or `schemaless_reader`.

Let me know if this would still be useful and if you think this would resolve the issue.

**Comment by costa** [comment]
Thanks guys, I've kinda lost interest in this for the period, and I'm a no Python expert to review the code or to help with the design decisions, so just letting you know...
