### ISSUE TITLE
Maybe change wrappers in six so that they match py3 style syntax

### ISSUE THREAD

**Issue by scottbelden** [tebeka/fastavro#123]
Right now `six` wraps py2/py3 functions with py2 style names. For example, `iteritems`, `iterkeys`, `itervalues`, and `xrange`. It might make sense to change these to py3 style: `items`, `keys`, `values`, and `range`.

Or maybe just better to wait until python 2 support is dropped at some point in the future...

**Comment by barrywhart** [comment]
Since the `six` module in `fastavro` is modeled after the [`six` library](https://pypi.python.org/pypi/six), I think it'd be a good idea to stay aligned with it.

http://pythonhosted.org/six/#object-model-compatibility

**Comment by scottbelden** [comment]
Yeah, that's a good point.
