### ISSUE TITLE
Support BinaryEncoder

### ISSUE THREAD

**Issue by pet0ruk** [tebeka/fastavro#14]
It would be nice (at least for me) to support the equivalent of BinaryEncoder() in Apache's Avro.  This work is basically done as far as I can tell (in fact my tests involved commenting code out with no additions).  But ultimately it's just a method to print the records without any header or length information.  I was able to achieve this by simply commenting out any of the writes unrelated to the record itself.

I commented out the following lines in writer.py:
280, 327, 331, 335

Obviously though, editing the library is not the best option, so a way to do this natively would be nice.

Thanks for your work!

**Comment by tebeka** [comment]
Thanks for reporting. I'll do my best to have an answer by the end of the week (just got back from 2 week vacation and cleaning things...)

**Comment by pet0ruk** [comment]
It's for the same use-case as BinaryEncoder in Avro.  It's useful when you want to send data from one place to another, where both places already have the schema on each end.  They require nothing but the encoded data.

There's a similar request with reasoning in pyavroc - https://github.com/Byhiras/pyavroc/issues/1

**Comment by scottbelden** [comment]
I believe this should do what you are looking for: https://github.com/tebeka/fastavro/pull/24

We do the same thing as well.

**Comment by tebeka** [comment]
Closing since PR #24 seems to fix this.
