### ISSUE TITLE
Follow documented best practices for distributing Cython modules

### ISSUE THREAD

**Issue by barrywhart** [tebeka/fastavro#144]
Issue #142 reminded me of a couple Cython packaging changes we should consider:
* Distribute `.c` files as well as `.pyx` files
* Do not enable Cython compilation by default

Both these practices are recommended in the [Cython documentation](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules).

The advantage is that it results in a less complex installation process on the target machine (just compiling C code instead of installing Cython and generating C code). It avoids any potential Cython version incompatibilities as well (i.e. if two different packages require different versions of Cython).

I'd be happy to help out making these changes if someone (@scottbelden?) can tell me how you currently prepare source packages for upload to PyPI.

**Comment by scottbelden** [comment]
I believe the `.c` files should be in the source distribution. I just downloaded the 0.17.2 tarball from pypi and it has the c files. As far as how packing is done, it's via `make publish` which just calls the `publish.sh` script. I think this issue is related to https://github.com/tebeka/fastavro/pull/145

**Comment by barrywhart** [comment]
One thing I wasn't sure about, when I ran `python setup.py sdist`, it would include the `.c` files if they already existed, but if they didn't, it wouldn't create them. Maybe `publish.sh` takes care of this. We'd also want to verify that if the `.c` files are present in the archive, it uses them instead of recreating them, etc. I probably should've checked all this before creating an issue, sorry about that!

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/157
