### ISSUE TITLE
Consider removing ujson from the codebase

### ISSUE THREAD

**Issue by scottbelden** [tebeka/fastavro#150]
`ujson` was added via https://github.com/tebeka/fastavro/pull/104 but I wonder if this was a mistake. There is an open issue about whether the package is even maintained anymore (and no response as of creating this issue): https://github.com/esnme/ultrajson/issues/291

There are lots of issues in their tracker that aren't getting any response and even outstanding PRs that aren't getting addressed.

The last update to the package was almost a year ago.

Additionally, we have to do a lot of special casing because [it's not a drop in replacement](https://github.com/esnme/ultrajson/issues/252).

**Comment by barrywhart** [comment]
I don't see much point in using a non-standard JSON package. It's only used when writing the header, right? It seems like:

* In most cases, files will have one header and many records, so it' not important.
* If writing a lot of small files with the same schema, maybe provide a way to cache the JSON string version of the schema, so it will only need to be converted once.
