### ISSUE TITLE
Writing with schemas defined in different files gives UnknownType errors

### ISSUE THREAD

**Issue by hajapy** [tebeka/fastavro#159]
I've been trying to make use of avro schemas in separate files, which is supposed to be possible: https://github.com/tebeka/fastavro/blob/b53954df0c6e5f466316792671c28839510d73e9/fastavro/_schema.pyx#L110-L116

Even using the checked in examples https://github.com/tebeka/fastavro/blob/master/tests/avro-files/Child.avsc and https://github.com/tebeka/fastavro/blob/master/tests/avro-files/Parent.avsc, I found that this is not working.

If one loads the Parent.avsc schema, you get:
```
# inside fastavro/tests/avro-files
schema = fastavro.schema.load_schema('Parent.avsc')
{'fields': [{'name': 'child', 'type': 'Child'}],
 'name': 'Parent',
 'type': 'record'}
```

Now, if you try to serialize records with this schema, you get `UnknownType` error
```
In [6]: with open('parent.avro', 'wb') as out:
   ...:     fastavro.writer(out, schema, [{'child': []}])
   ...:
---------------------------------------------------------------------------
UnknownType                               Traceback (most recent call last)
<ipython-input-6-071f2d2cfde3> in <module>()
      1 with open('parent.avro', 'wb') as out:
----> 2     fastavro.writer(out, schema, [{'child': []}])
      3
fastavro/_write.pyx in fastavro._write.writer()
fastavro/_write.pyx in fastavro._write.Writer.__init__()
fastavro/_write.pyx in fastavro._write.acquaint_schema()
fastavro/_schema.pyx in fastavro._schema.extract_named_schemas_into_repo()
fastavro/_schema.pyx in fastavro._schema.extract_named_schemas_into_repo()
UnknownType: Child
```

That seems strange, seeing as the "Child" reader is indeed properly "acquainted" 
```
fastavro.read.READERS
{'Child': <cyfunction acquaint_schema.<locals>.<lambda>.<locals>.<lambda> at 0x103659830>,
 'Parent': <cyfunction acquaint_schema.<locals>.<lambda>.<locals>.<lambda> at 0x1036598e8>, ...}
```

Does the writer need to prepare the schema in a fully dereferenced form before being able to write? My understanding was that schemas embedded in avro files were fully self-contained, so perhaps this step is missing. I don't think serializing with such schemas is covered in the tests  https://github.com/tebeka/fastavro/blob/23b52f3376bb1777d55d9d239ed021ff558a191a/tests/test_fastavro.py#L219-L229

**Comment by kkirsanov** [comment]
You can temporarily fix this by calling ```fastavro.acquaint_schema``` for Child schema manually.

**Comment by kkirsanov** [comment]
Hmm.
I found this recipe https://github.com/tebeka/fastavro/issues/55

**Comment by hajapy** [comment]
Thanks for the suggestion. Indeed, acquainting the writer with the Child schema does get us past one hurdle here, in that fastavro allows us to serialize some records:

```
In [1]: import fastavro
In [2]: records = [{"child": {}}, {"child": {}}]
In [3]: schema = fastavro.schema.load_schema('Parent.avsc')
In [4]: fastavro.acquaint_schema(fastavro.schema.load_schema('Child.avsc'))
In [5]: with open('parent.avro', 'wb') as out:
   ...:     fastavro.writer(out, schema, records)
```
all good so far, except now if we try to read the contents:

```
fastavro --schema parent.avro
Traceback (most recent call last):
  File "/Users/x/.local/share/virtualenvs/y/bin/fastavro", line 11, in <module>
    sys.exit(main())
  File "/Users/x/.local/share/virtualenvs/y/lib/python3.6/site-packages/fastavro/__main__.py", line 64, in main
    reader = avro.reader(fo)
  File "fastavro/_read.pyx", line 678, in fastavro._read.iter_avro.__init__
  File "fastavro/_schema.pyx", line 163, in fastavro._schema.acquaint_schema
  File "fastavro/_schema.pyx", line 100, in fastavro._schema.extract_named_schemas_into_repo
  File "fastavro/_schema.pyx", line 69, in fastavro._schema.extract_named_schemas_into_repo
fastavro._schema_common.UnknownType: Child
```

It seems to me, being only somewhat familiar with the code here, that although fastavro knows about all the types it needs for ser/deser after all schemas and sub-schemas are acquainted, it doesn't prepare a fully self-contained schema to write into the avro file.

**Comment by scottbelden** [comment]
@hajapy I believe https://github.com/tebeka/fastavro/pull/160 should resolve this. I fixed the test in tests/test_fastavro.py:test_compose_schemas so that it now checks for both the `Child` and `Parent` schemas in both the `READERS` and `WRITERS`.

With the changes I was able to run your example without an error:

```python
In [1]: import fastavro

In [2]: from io import BytesIO

In [3]: schema = fastavro.schema.load_schema('tests/avro-files/Parent.avsc')

In [4]: s = BytesIO()
   ...: fastavro.writer(s, schema, [{'child': []}])
   ...: print(s.getvalue())
   ...: 
b'Obj\x01\x04\x14avro.codec\x08null\x16avro.schema\x98\x01{"name":"Parent","type":"record","fields":[{"name":"child","type":"Child"}]}\x00\xf5\x1f\xa8O\xc9\x0bj\x08\xa3\x10\xcd!m\x0e\x1e\xca\x02\x00\xf5\x1f\xa8O\xc9\x0bj\x08\xa3\x10\xcd!m\x0e\x1e\xca'
```

**Comment by hajapy** [comment]
@scottbelden thanks for looking into it. I think the acquainting the reader and writer when you load the schema is good, but I think there is still something missing. 

You can see plainly that the embedded schema doesn't define Child, so anyone trying to read this avro file without the original writer schema will not be able to.

Can confirm even on your branch:

```
In [1]: with open('parent.avro', 'wb') as f:
   ...:     f.write(b'Obj\x01\x04\x14avro.codec\x08null\x16avro.schema\x98\x01{"name":"Parent","type":"record","fields":[{"name":"child","t
   ...: ype":"Child"}]}\x00\xf5\x1f\xa8O\xc9\x0bj\x08\xa3\x10\xcd!m\x0e\x1e\xca\x02\x00\xf5\x1f\xa8O\xc9\x0bj\x08\xa3\x10\xcd!m\x0e\x1e\xca
   ...: ')
   ...:

In [2]:
Do you really want to exit ([y]/n)?
(fastavro-qZB9hzSx) ➜  fastavro git:(6b9e222) ✗ fastavro parent.avro
Traceback (most recent call last):
  File "/Users/x/.local/share/virtualenvs/fastavro-qZB9hzSx/bin/fastavro", line 11, in <module>
    load_entry_point('fastavro', 'console_scripts', 'fastavro')()
  File "/Users/x/workspace/forks/fastavro/fastavro/__main__.py", line 64, in main
    reader = avro.reader(fo)
  File "fastavro/_read.pyx", line 689, in fastavro._read.iter_avro.__init__
    acquaint_schema(self.writer_schema)
  File "fastavro/_read.pyx", line 614, in fastavro._read.acquaint_schema
    extract_named_schemas_into_repo(
  File "fastavro/_schema.pyx", line 100, in fastavro._schema.extract_named_schemas_into_repo
    namespaced_name = extract_named_schemas_into_repo(
  File "fastavro/_schema.pyx", line 69, in fastavro._schema.extract_named_schemas_into_repo
    raise UnknownType(schema)
fastavro._schema_common.UnknownType: Child
```

**Comment by scottbelden** [comment]
I see. That's a bit trickier. Let me see what I can do.

**Comment by hajapy** [comment]
This may be helpful. I realized that if I put Child.avsc and Parent.avsc into a single schema file, I get get everything working:

`Combo.avsc`
```
[
  {
    "type": "record",
    "name": "Child",
    "fields": []
  },
  {
    "type": "record",
    "name": "Parent",
    "fields": [
      {
        "name": "child",
        "type": "Child"
      }
    ]
  }
]
```

```
In [1]: import fastavro
In [2]: schema = fastavro.schema.load_schema('Combo.avsc')
In [3]: records = [{"child": {}}, {"child": {}}]
In [4]: with open('parent.avro', 'wb') as out:
   ...:     fastavro.writer(out, schema, records)
   ...:
```

Now, I see this:

```
(fastavro-qZB9hzSx) ➜  avro-files git:(6b9e222) ✗ fastavro --schema parent.avro
[
 {
  "type": "record",
  "name": "Child",
  "fields": []
 },
 {
  "type": "record",
  "name": "Parent",
  "fields": [
   {
    "name": "child",
    "type": "Child"
   }
  ]
 }
]
(fastavro-qZB9hzSx) ➜  avro-files git:(6b9e222) ✗ fastavro parent.avro
{"child": {}}
{"child": {}}
```

**Comment by hajapy** [comment]
One additional note: the order of the schemas matters here. If you put Parent before Child, you still get the UnknownType error. So I think the solution is to combine the schemas into an array sorted by dependency order. Tricky, but should be solvable.

**Comment by scottbelden** [comment]
Good point. I had forgotten that schemas could be lists, not just dictionaries. That made things a lot easier. I updated by PR branch and added a test for the error when reading, so I think it should be good now.

**Comment by hajapy** [comment]
Great stuff @scottbelden, your branch is working for me now and seems to handle this issue nicely. I like that using load_schema returns the schema as it will be used in the writer and that it isn't some behind-the scenes conversion that goes on.

**Comment by scottbelden** [comment]
Great. Will probably merge/release shortly.
