### ISSUE TITLE
Exposing ``ReaderBase`` to python runtime

### ISSUE THREAD

**Issue by rmax** [tebeka/fastavro#162]
Hi, I maintain `dask-avro` and we had an issue https://github.com/rmax/dask-avro/issues/2 with the latest version.

We depend on the internal function `_iter_avro` to [read partial blocks](https://github.com/rmax/dask-avro/blob/master/src/dask_avro/__init__.py#L80) in order to process an avro file in parallel. In the last release [the cython-optimized function](https://github.com/tebeka/fastavro/blob/master/fastavro/_read.pyx#L626) requires the type `ReaderBase` which is not exposed to python.

Would you considering either exposing ``ReaderBase`` class/subclasses or make ``_iter_avro`` part of the public API?

**Comment by scottbelden** [comment]
I believe the `FileObjectReader` should be use-able.

I think this is basically what you are trying to do and it worked for me:

```python
from fastavro._read import _iter_avro as iter_cy
from fastavro._read import FileObjectReader
from io import BytesIO

stream = BytesIO(b'\x02\x1c\x1adefault_valuef\x801#m\xc1*\x15]\xd4o\xb4T#RU')
schema = {'type': 'record', 'fields': [{'type': 'string', 'default': 'default_value', 'name': 'default_field'}]}
codec = 'null'
header = {'magic': b'Obj\x01', 'meta': {'avro.codec': b'null', 'avro.schema': b'{"type": "record", "fields": [{"type": "string", "default": "default_value", "name": "default_field"}]}'}, 'sync': b'f\x801#m\xc1*\x15]\xd4o\xb4T#RU'}

for record in iter_cy(FileObjectReader(stream), header, codec, schema, schema):
    print(record)
```

Let me know if that's what you are trying to achieve.

As for exposing `_iter_avro`, it would require more thought.

**Comment by rmax** [comment]
Yes! That did the trick. Thanks.
