### ISSUE TITLE
Writing and reading sets boolean to False

### ISSUE THREAD

**Issue by DoHe** [tebeka/fastavro#17]
I use following schema:

```
{'fields': [{'name': 'flag', 'type': 'boolean'}],
 'name': 'test',
 'type': 'record'}
```

to write this datum:

```
{"flag":True}
```

Serializing results in this byte string:

```
b'Obj\x01\x04\x14avro.codec\x08null\x16avro.schema\xa6\x01{"name": "test", "type": "record", "fields": [{"type": "boolean", "name": "flag"}]}\x00:\xea\xf7\x8cV\xa0:4\\\xd0A\x85\xa4\x05\xcf\xe9\x02\x021:\xea\xf7\x8cV\xa0:4\\\xd0A\x85\xa4\x05\xcf\xe9'
```

and deserializing it gives me this datum:

```
[{'flag': False}]
```

i.e. the True has been turned to False. The deserialized schema is intact.

Additionally, writing a datum like `{}` works just fine (although it should throw an Exception) and when reading back, I again get:

```
[{'flag': False}]
```

I'm using python3, but have reproduced the problem on python2 as well. I also tried the pure python version without the compiled cython extensions and have the same problem there. I use a BytesIO as the fo, if this matters.

**Comment by tebeka** [comment]
Thanks for reporting! Will try to have a look soon-ish.

**Comment by ahane** [comment]
an avro file containing just a True value (which fails when added to the test files)
https://github.com/ahane/fastavro/blob/booleans/tests/avro-files/bool.avro

**Comment by DoHe** [comment]
If I serialize with the reference implementation and deserialize with fastavro, everything works just fine, so the problems seems to be in the serialization already.

**Comment by scottbelden** [comment]
I put a PR in to fix this. Located here: https://github.com/tebeka/fastavro/pull/18
