### ISSUE TITLE
timestamp logicalType return naive datatime objects

### ISSUE THREAD

**Issue by abrarsheikh** [tebeka/fastavro#171]
I noticed that the Reader returns a naive datetime python object for `timestamp-mills` and `timestamp-micros`. What was the reasoning behind this implementation?

In my opinion the expected behavior should be that the writer take in a tzaware datetime python object, then normalizes it to timestamp from epoch before storing it as `int` or `long`. On the reader side it should convert the timestamp from epoch into a tzaware date time python object (where timezone is UTC or anything). This is how the apache/avro for java implements timestamp logical type. And I have done the similar implementation in the [apache/avro for python](https://github.com/apache/avro/pull/207)

**Comment by kkirsanov** [comment]
I agree.

I'll do it this weekend.

**Comment by abrarsheikh** [comment]
@kkirsanov awesome, thanks for taking point on this :)

**Comment by lsterk** [comment]
@kkirsanov have you been able to take up this issue? Otherwise I can take a stab at this.

**Comment by kkirsanov** [comment]
@lsterk please, take this.
You're welcome.
I was too busy at work.

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/174
