### ISSUE TITLE
More descriptive validation errors

### ISSUE THREAD

**Issue by rhaarm** [tebeka/fastavro#172]
Getting really deep into working with Avro schemas from an old dynamic json system and have found the conversion difficult because error messages are no descriptive.

After looking over the validation piece, we found thay the basic validation function could use some modifications. I will be looking to publish changes in the future referencing this issue.

I'm not familiar with cython development, so I'll try my best to do the cython side as well but may require assistance.

**Comment by scottbelden** [comment]
Do you mind giving an example of what a current error is and what you think would be better? I had some ideas about this a long time ago in https://github.com/tebeka/fastavro/pull/52 and https://github.com/tebeka/fastavro/pull/53 but ultimately neither of those were merged. My idea at the time was to have the exception include some information such as the following:

```python
Path is: <record[0]>.<field[aa]>.<field[b]>.<field[c]>
Datum is 2 of type <type 'str'>
Expected avro schema type: int
```

**Comment by rhaarm** [comment]
I have the Python version written, need to write unittest, but all existing test are passing.

Need to write cython version as well after I proofed the regular Python version.

**Comment by scottbelden** [comment]
Would you mind going ahead and pushing a branch or starting a PR? I tend to do the python side first as well, and that way we can make sure that end of it looks good and prevent having to fix both the python and cython if anything needs modifying.

**Comment by rhaarm** [comment]
How to create a PR to a non existing branch on repo? or do you want commuted to master?

https://github.com/rhaarm/fastavro/tree/Validators

**Comment by rhaarm** [comment]
@scottbelden see my previous comment

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/182
