### ISSUE TITLE
Please provide guidelines for contributing

### ISSUE THREAD

**Issue by mvallebr** [tebeka/fastavro#175]
Some features listed here might be really important for our company, so depending on how important they become, we could think on spending resources to contribute to this project. 

However, even to consider this, we need to have guidelines for contributing, a mailing list, etc. 

I haven't found anything related to this neither in the README nor in the official website. Could you please provide instructions?

**Comment by scottbelden** [comment]
I'll try to see if I can come up with something more formal, but in general bugs and new feature requests typically start as github issues where they can be discussed. I try to resolve these as time affords, but PRs are welcome from all.

There is currently no mailing list. Some questions that could be posed to a mailing list currently come up as github issues and I don't think that has been an issue as the volume isn't that large.

**Comment by mvallebr** [comment]
Please consider this PR - https://github.com/tebeka/fastavro/pull/177

I will follow this for other issues once approved

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/177
