### ISSUE TITLE
Support for sub schemas and unknown logical types

### ISSUE THREAD

**Issue by todpunk** [tebeka/fastavro#178]
I am debating adding support for "schema" types and "unknown" logical types.  I'm thinking of using fastavro for some avro data I have.  It's change data from a database, so there are two scenarios here that fastavro doesn't like.  The example here:

```
{
    "name":"special_nullable_string",
    "type": ["null", {
        "type":"string",
        "logicalType":"varchar",
        "metadata":30 } ]
}```

The first is having a logicaltype of "varchar" for a string base type.  The second is having a subschema as a type, which is perfectly valid avro (this is how you get an avro schema that is not flat).

Would this be a welcome addition, and if so, I believe the reader is easy (I've already written two tests I'll add in a comment here) but the writer is escaping my immediate thoughts.  Any pointers on how to best approach that would be appreciated.

**Comment by todpunk** [comment]
In `test_logical_types.py` I have added what I believe to be the cases I would need.  Any others I might be missing?  I don't know the code base well enough to know caveats.

```

unknown_type_schema = {
    "name":"special_string",
    "type": {
        "type":"string",
        "logicalType":"varchar",
        "metadata":30 }
    }

def test_unknown_logical_type():
    """
    Any extension to logical types are allowed in the spec, so we should default to the underlying type instead of failing
    """
    data1 = "I am a string"
    converted  = serialize(unknown_type_schema, data1)
    data2 = deserialize(unknown_type_schema, converted)
    assert (data1 == data2)
    
nullable_type_schema = {
    "name":"special_nullable_string",
    "type": ["null", {
        "type":"string",
        "logicalType":"varchar",
        "metadata":30 }]
    }

def test_nullable_unknown_logical_type():
    """
    It is valid to have types that can be in several states, like a nullable field in a database
    """
    data1 = "I am a string"
    data2 = None
    converted = serialize(nullable_type_schema, data1)
    nulled = serialize(nullable_type_schema, data2)
    data1_2 = deserialize(nullable_type_schema, converted)
    data2_2 = deserialize(nullable_type_schema, nulled)
    assert(data1 == data1_2)
    assert(data2 == data2_2)
```

**Comment by scottbelden** [comment]
I agree that an unknown logical type shouldn't give an error (as per the spec). However, shouldn't the test be more like this?

```python
def test_unknown_logical_type():
    """Any extension to logical types are allowed in the spec, so we should
    default to the underlying type instead of failing
    """
    unknown_type_schema = {
        "type": "string",
        "logicalType": "varchar",
        "metadata": 30
    }
    data1 = "I am a string"
    converted = serialize(unknown_type_schema, data1)
    data2 = deserialize(unknown_type_schema, converted)
    assert (data1 == data2)
```

With that, I get a `KeyError: 'string-varchar'` which we should be able to resolve in the reader/writers by changing https://github.com/tebeka/fastavro/blob/master/fastavro/_write_py.py#L491 to be like so:

```python
    if logical_type:
        prepare = LOGICAL_WRITERS.get(logical_type)
        if prepare:
            data = prepare(datum, schema)
            return fn(fo, data, schema)
    return fn(fo, datum, schema)
```

As for the subschema as a type, I'm not sure I understand. Could you give an example?

**Comment by todpunk** [comment]
Technically speaking, both test cases are an example of a subschema as a type (the JSON object with its own type where `"type": {"type": "string"}` is equivalent to `"type": "string"` but the first is still a subschema).  

A more realistic example might be like this:

```
{   "type" : "record",
  "name" : "t_customers",
  "fields" : [ {
    "name" : "name",
    "type" : {
      "type" : "string",
      "logicalType" : "varchar",
      "maxLength" : 200
    },{
     "name": "address",
     "type": "record",
     "fields": [ {
          "name": "street",
          "type": {
            "type": "string",
            "logicalType" : "varchar",
            "maxLength" : 240
          }
        },{
          "name": "city",
          "type": {
            "type": "string",
            "logicalType" : "varchar",
            "maxLength" : 80
          }
        },{
          "name": "zip",
          "type": {
            "type": "string",
            "logicalType" : "varchar",
            "maxLength" : 18
          }
        }
    ] }
] }
```

You can see how this might be a message from a GraphQL style call or some document store.  Technically in some tooling the message itself can be referencing other schema types instead of making it a record.  This is a similar format to the results of a CDC tool I've got some Avro files from.  Spark-avro is what they're being processed into, but I prototyped some stuff with fastavro and it didn't work.

I specifically ran into the varchar issue, but in looking at the code I saw no place where it had a "schema" type.  I could easily be wrong here and maybe it would just work?

**Comment by scottbelden** [comment]
If I alter your schema to look like the following, it works (note I had to comment the `logicalType` due to the second issue of not ignoring those properly):

```python
def test_unknown_logical_type():

    unknown_type_schema = {
        "type": "record",
        "name": "t_customers",
        "fields": [{
            "name": "name",
            "type": {
                "type": "string",
                # "logicalType": "varchar",
                "maxLength": 200
            },
        }, {
            "name": "address",
            "type": {
                "type": "record",
                "name": "t_address",
                "fields": [{
                    "name": "street",
                    "type": {
                        "type": "string",
                        # "logicalType": "varchar",
                        "maxLength": 240
                    }
                }, {
                    "name": "city",
                    "type": {
                        "type": "string",
                        # "logicalType": "varchar",
                        "maxLength": 80
                    }
                }, {
                    "name": "zip",
                    "type": {
                        "type": "string",
                        # "logicalType": "varchar",
                        "maxLength": 18
                    }
                }]
            }
        }]
    }

    data1 = {
        'name': 'foo',
        'address': {
            'street': '123 street',
            'city': 'city',
            'zip': '00000'
        }
    }
    converted = serialize(unknown_type_schema, data1)
    data2 = deserialize(unknown_type_schema, converted)
    assert (data1 == data2)
```

The main change was in the `address` field where I changed the `type` from `record` to the json object. Or is you point that the `type` should be able to be `record` without needing a nested json object?

**Comment by rhaarm** [comment]
@todpunk your most recent schema is broken, I just pasted that code in Schema Registry and it got rejected, looks like you are missing a closing bracket '}' between "name" and "address" field.

@scottbelden I'll see if I can get the writer and reader updated sooner with the extra logic around logical_type. If anything the logicalType should default to the standard type if the logicalType doesn't exist in the "Known" logicalTypes. This will also help with #173 which should just be a function "registers" to the LOGICAL_READERS and LOGICAL_WRITERS, if the writer or reader functions are left out, then it should refer to the base type.

**Comment by scottbelden** [comment]
@rhaarm Thanks! I think adding the check to make sure the logical type is actually defined should be pretty straight forward, but let me know if you need any help.

**Comment by todpunk** [comment]
@rhaarm that is likely, yes.  My schema was made up by hand at the time =c) Sorry for missing that, will update.  If you're doing a pull request I will sit tight.  Feel free to highlight me and I'll test and add a vote your way for that.

**Comment by scottbelden** [comment]
@todpunk After looking again at your message about the subschema, I'm pretty sure that should already be possible. For example, I think this test does what you mentioned:

https://github.com/tebeka/fastavro/blob/4732e32a2fb2c9c54d5c921f693c9f93df5179ff/tests/test_fastavro.py#L257-L272

**Comment by rhaarm** [comment]
@todpunk Looks like the fix will take a bit of time, `validate` function needs to be updated or how the `write_union` function, since it's using `validate`. I've already had an idea around this for a month now because I wanted to make changes to how validation works anyways, but this may take a few days.

**Comment by todpunk** [comment]
@scottbelden alright, that would be a good example of that, yes.  Good find.

**Comment by scottbelden** [comment]
I think this should be resolved so I'm going to close it. Part of this discussion talked about custom logical types, but I think that should be done [on the other issue](https://github.com/tebeka/fastavro/issues/173).
