### ISSUE TITLE
Prepare UUID

### ISSUE THREAD

**Issue by rhaarm** [tebeka/fastavro#179]
https://github.com/tebeka/fastavro/blob/master/fastavro/_write_py.py#L79

Could be used for casting anything to a String, should this be the case, or should we be stricter and do similar to the `if isinstance(data, datetime.datetime)` and on the `else` return what was sent in?

**Comment by scottbelden** [comment]
It does seem a little odd that that one is different from the others. It probably doesn't hurt to have the check (although we'd want to check for a `uuid.UUID` type)...

**Comment by rhaarm** [comment]
Also, I'm adding in comments to all prepare functions as well.

**Comment by rhaarm** [comment]
PR #181 closing
