### ISSUE TITLE
Issue when reading long values

### ISSUE THREAD

**Issue by rsoma-grounds** [tebeka/fastavro#197]
Hi all,
 
Fastavro seems to have a bug in reading large numbers in a field of type `long`. The issue occurs for numbers (>~4611686018427387904). 

Attaching a simple example to reproduce the error.
(The correct number is `9223371823962989837` but fastavro reads it as `-212891785971`)

thanks,
Ram.
[big_number.avro.zip](https://github.com/tebeka/fastavro/files/2017827/big_number.avro.zip)

**Comment by scottbelden** [comment]
It looks like there might be a difference in the cython code as if I run in pure python it's fine. Should be easy to fix. Thanks for the report.
