### ISSUE TITLE
Write support

### ISSUE THREAD

**Issue by darkjh** [tebeka/fastavro#2]
Just to know if it's in planning to add write support?

**Comment by tebeka** [comment]
Yes there is a plan :) However I'm not in the Hadoop ecosystem for a while now.
There's also some work in the [write](https://bitbucket.org/tebeka/fastavro/src/a82b3647c0525301caf121f48837ea762b5de54d/?at=write) branch, however there's a bug in the header writing and I left it alone for a while now.

Patches are welcomed ... ;)

**Comment by darkjh** [comment]
Thanks for the information.
Can you sync the code (write branch) to github? I'll try to have a look at the write part.

**Comment by tebeka** [comment]
Sure. I'll do it tomorrow.

**Comment by tebeka** [comment]
It's in the [w](https://github.com/tebeka/fastavro/tree/w) branch (due to hg-git limitation can't name it `write`).

**Comment by mjwillson** [comment]
Hey all -- I noticed there's a `fastavro.write` function in the API -- what's the status of this? If it doesn't work at all maybe it'd be better to remove it for now and leave it on this branch?

@darkjh, wondering if you got anywhere with that header writing issue?

**Comment by tebeka** [comment]
@mjwillson Oops, shouldn't have been there. Updates source but getting 500 on pypi when trying to upload - will try later. Thanks!
