### ISSUE TITLE
schemaless writer doesn't adhere to avro spec

### ISSUE THREAD

**Issue by scottbelden** [tebeka/fastavro#203]
The [avro spec](https://avro.apache.org/docs/current/spec.html#single_object_encoding) says that a single record encoded without a schema should have have a two byte marker of `C3 01` and then an 8 byte little endian fingerprint before the actual binary. The `schemaless_writer` doesn't currently write out these 10 bytes (because it was implemented before the spec defined a single object encoding) and the `schemaless_reader` doesn't expect them.

A change here would be a breaking change, so we should be aware of that.

**Comment by rhaarm** [comment]
We could create a new set of functions that essentially call schemless_funcs but do the byte order mark, etc before calling the write/reader.

**Comment by scottbelden** [comment]
I closed this because after I posted it I re-read https://github.com/tebeka/fastavro/issues/201 and realized they were the same thing. We can keep discussion over at https://github.com/tebeka/fastavro/issues/201.
