### ISSUE TITLE
Add some coverage reporting

### ISSUE THREAD

**Issue by scottbelden** [tebeka/fastavro#211]

**Comment by chobeat** [comment]
I might work on this but what we want to do? There's the pytest-cov option but it breaks Intellij/PyCharm debugger and I always find it extremely annoying. On the other side it takes a second to activate it. Do we want to opt for an external tool? 

I believe we also want to integrate it with codecov and travis (and have a fancy badge on the project page). I've never done this but I would like to learn.

**Comment by scottbelden** [comment]
Thanks for the interest. There are a couple of different ways to do this from simple to more complex. Here are some thoughts I've had:

1. Print the coverage after running the tests (simplest)
I think all this would involve is adding `coverage` to the `developer_requirements.txt` and then changing this line:
https://github.com/tebeka/fastavro/blob/edbadfa82ad993efbe43d1d79b6b8e4701f4558e/run-tests.sh#L21
To be 
```
PYTHONPATH=${PWD} python -m coverage run --source fastavro -m pytest -v $@ tests
```

2. Have the coverage report as part of the PR report (more complicated)
There is a `codecov` bot that does this. I know many projects that use it, but I've never set it up.

3. Make sure the coverage reports both cython and python coverage (most complicated)
I did something like this for another project and it involved having an environment variable that would turn on cython profiling: https://github.com/scottbelden/ckerl/blob/b55478e099702dbe8e4f69748b876d9bf4529d85/setup.py#L15-L20. Then we'd modify this line: https://github.com/tebeka/fastavro/blob/edbadfa82ad993efbe43d1d79b6b8e4701f4558e/run-tests.sh#L19 so that it would also set `CYTHON_TRACE=1`

Any help even with just the first simpler case would be greatly appreciated. Let me know if there's anything I can clear up. Thanks!

**Comment by chobeat** [comment]
Ok, it was much easier than I expected. I believe it's enough that you create an account on codecov and activate it for the fastavro repo. I have the PR ready

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/216

I will see about getting the codecov account going.
