### ISSUE TITLE
Incorrect Makefile?

### ISSUE THREAD

**Issue by sanjayankur31** [tebeka/fastavro#215]
https://github.com/tebeka/fastavro/blob/master/Makefile#L15 specifies C files, but there aren't any in the directory there.

**Comment by scottbelden** [comment]
They get auto-generated when running `make` or `make fresh`. They aren't checked in to the repository though.

**Comment by sanjayankur31** [comment]
Ah, yeh, using the required environment variable works. Closing. Thanks! :)
