### ISSUE TITLE
Raise error on boolean value which is not 0 or 1

### ISSUE THREAD

**Issue by tebeka** [tebeka/fastavro#27]
Currently we accept 0 as boolean False and anything else as True. However [the spec says](https://avro.apache.org/docs/1.7.7/spec.html#binary_encoding): `a boolean is written as a single byte whose value is either 0 (false) or 1 (true).`

Maybe we should be stricter?

**Comment by scottbelden** [comment]
For what it's worth, the official avro python client does the opposite. It accepts 1 as boolean True and everything else as False.

https://github.com/apache/avro/blob/trunk/lang/py/src/avro/io.py#L167-L172

**Comment by tebeka** [comment]
@scottbelden Well, the spec says 1 is true and 0 is false. Everything else should be an error.
Also this is very un-pythonic since in Python 0 if false and almost everything else is true :)

OTOH - [this is what the Java code does](http://svn.apache.org/viewvc/avro/trunk/lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java?view=markup) (line 123) ...

**Comment by scottbelden** [comment]
I think throwing the error seems reasonable.

**Comment by tebeka** [comment]
The `fastavro.writer.valiate` function does that.
