### ISSUE TITLE
Release 0.8.0 made but not on master

### ISSUE THREAD

**Issue by mjwillson** [tebeka/fastavro#3]
https://pypi.python.org/pypi/fastavro/0.8.0

Is this intentional? I was puzzled why I was pulling in a 0.8.0 version but master is still on 0.7.x

**Comment by tebeka** [comment]
I probably did something bad with hg-git. Will fix soon, sorry for that.
Main repo is at https://bitbucket.org/tebeka/fastavro this one is a mirror.

**Comment by mjwillson** [comment]
No prob, sorry didn't realise this was only a mirror.

**Comment by tebeka** [comment]
IMO this is fixed now
