### ISSUE TITLE
Should code be more strict about record names?

### ISSUE THREAD

**Issue by scottbelden** [tebeka/fastavro#32]
Currently no errors are thrown for records that don't have a "name" field. According to the spec, "name" is a required field. Should this (https://github.com/tebeka/fastavro/blob/master/fastavro/schema.py#L33) be changed so that an error is thrown if the field isn't provided? Some tests would need to be updated as well.

**Comment by tebeka** [comment]
That's a good point. OTOH the robustness principal says "Be conservative in what you send, be liberal in what you accept". Will think about this a bit more (maybe a `strict` flag)

**Comment by brianbruggeman** [comment]
I would argue that it's better to be compliant here for interoperability with other languages/implementations.

**Comment by tebeka** [comment]
@brianbruggeman Is that what other language are doing? (mostly Java)

**Comment by brianbruggeman** [comment]
@tebeka Yes.  To be clear, 'name' as a field is required when not using a primitive type.  But I suspect most data falls under non-trivial schemas (i.e. records or possibly multiple record types).

You can read about the schema spec here:  https://avro.apache.org/docs/1.8.1/spec.html#schemas

**Comment by tebeka** [comment]
OK, thanks. Do you mind submitting a PR? (if no I'll do it).
