### ISSUE TITLE
Rename fastavro.writer

### ISSUE THREAD

**Issue by tebeka** [tebeka/fastavro#36]
We currently have `fastavro.writer` module but also a `writer` object in `__init__.py`. This makes it hard while debugging to import the `writer` module.

**Comment by ze-phyr-us** [comment]
This is a bigger problem than just debugging. When you import the reader/writer submodules, the import overwrites the `fastavro.reader` or `fastavro.writer` attributes with the imported modules:

```python
import fastavro
from fastavro.reader import SchemaResolutionError # or even just 'import fastavro.reader'

print(fastavro.reader)
```

```
$ python3 importtest.py
<module 'fastavro.reader' from 'XXX/env/lib/python3.5/site-packages/fastavro/reader.py'>
```

**Comment by tebeka** [comment]
Thanks! I'll try to work on it soon-ish. Patches are always welcomed ;)

**Comment by ze-phyr-us** [comment]
@tebeka I'm happy to submit a PR. What would be good names for the modules? `reading.py` and `writing.py`? `read.py` and `write.py`?

**Comment by tebeka** [comment]
@ze-phyr-us Not sure. Maybe `read.py` and `write.py`
Thanks!

**Comment by barrywhart** [comment]
This [PR](https://github.com/tebeka/fastavro/pull/114) addresses the issue.

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/137
