### ISSUE TITLE
Add support for writing records asyncronously

### ISSUE THREAD

**Issue by rodcarroll** [tebeka/fastavro#38]
Currently the fastavro.writer method expects a list of records and writes them at once.  I'd like to be able to write the file header, preserve some context, and then write each record as my application receives data, then make a final call to flush the output when finished.

**Comment by tebeka** [comment]
Thanks for reporting, will look into it soon-ish.

**Comment by LaurEars** [comment]
I second this request. It would be really useful to not have to generate a huge list in memory and then write them all at once. It would make for more pythonic loops.

**Comment by tebeka** [comment]
With the current design the `records` parameter is any iterable including a generator. This way you can write a generator that produces records when they become available the exit the generator when your done.

For example:
```python
def gen_records():
    while True:
        record = next_record()
        if not record:  #end of records
            return
         yield record

with open('records.avro', 'w') as out:
    writer(out, schema, gen_records())
```
