### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by mrocklin** [tebeka/fastavro#45]
Currently the functions within fastavro are not easy to inspect for interactive users.

```python
In [1]: import fastavro

In [2]: fastavro.writer?
Type:        cython_function_or_method
String form: <cyfunction writer at 0x7ff96e693df0>
Docstring:   <no docstring>
```

I find myself referring to the source code in order to determine suggested inputs.  I suspect that a small amount of effort here would significantly increase impact.

**Comment by tebeka** [comment]
Great point, will take care of it soon-ish. Thanks for reporting.

**Comment by mrocklin** [comment]
Hrm, it's still not clear to an interactive user what to provide to the writer function:

```python
In [1]: import fastavro

In [2]: fastavro.__version__
Out[2]: '0.9.8'

In [3]: fastavro.writer?
Type:        cython_function_or_method
String form: <cyfunction writer at 0x7f8275ab9328>
Docstring:   Write records to fo (stream) according to schema
```

The example with `reader` is much more clear

```python
In [4]: fastavro.reader?
Docstring:
Custom iterator over avro file.

Example:
    with open('some-file.avro', 'rb') as fo:
        avro = iter_avro(fo)
        schema = avro.schema

        for record in avro:
            process_record(record)
File:      ~/Software/anaconda/lib/python3.4/site-packages/fastavro/_reader.cpython-34m.so
Type:      type
```

But in both cases it would be great to see a signature and list of parameters.  Personally I use the numpydoc standard https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections

Of course, I'm just making requests without actually helping, so I'm happy with whatever you're willing to do :)

**Comment by tebeka** [comment]
@mrocklin You're right to make requests. I'll try to improve documentation - but I'm super busy in the next two weeks. Pull requests/patches are always welcomed ;)

**Comment by tebeka** [comment]
Add more docstrings. Closing for now.
