### ISSUE TITLE
Avro 1.8 Support

### ISSUE THREAD

**Issue by wkral** [tebeka/fastavro#47]
Perhaps this is in the works but I haven't seen any reference to 1.8 yet.

The major addition has been logical types: https://avro.apache.org/docs/1.8.0/spec.html#Logical+Types

In the serialization and deserialization of the avro data in the presence of a logical type of say `timestamp-millis` it would be nice if you passed a datetime object inside a dictionary that it would be serialized to a long unix timestamp. Similarly you'd get a datetime object back when deserializing with the correct precision set inside.

Naturally logical types should default to types inside the Python standard lib. But just because we use [arrow](http://crsmithdev.com/arrow/) objects, it would also be nice to have the ability to add to the serializers to accommodate different types and override the default deserializer for a given logical type.

**Comment by tebeka** [comment]
Thanks @wkral, this is a good idea. Maybe can be done in a similar way [Python's json](https://docs.python.org/3.5/library/json.html) does. Need to think about it.

I'm currently very busy so patches are more than welcomed :)

**Comment by wkral** [comment]
Thanks, I'll see what I can do in terms of sending Pull Requests. Would an incremental approach work well for you? I'm similarly quite busy but might be able to handle it better in smaller parts.

For example it might be easier to do it in these steps:

1. Allow 1.8 compliant schemas and ensure they don't throw any errors when used with logical types
2. Serializing stdlib types to avro data types
3. Deserialization to stdlib types
4. Type extentions and overrides

**Comment by tebeka** [comment]
Thanks.  Incremental approach will be great.

**Comment by kkirsanov** [comment]
https://github.com/tebeka/fastavro/pull/79 :)

**Comment by tebeka** [comment]
@kkirsanov You're right, thanks again.
