### ISSUE TITLE
fastavro gives a default value for unions with nulls that don't have a default value

### ISSUE THREAD

**Issue by movermeyer** [tebeka/fastavro#49]
This is somewhat related to #48. Given this example schema:

```
protocol test {
  record a {
    int x;
    union {null, int} y;
  }
}
```

the following should fail:

```
>>> data = StringIO.StringIO()
>>> fastavro.writer(data, schema, [{'val': {'x': 1}}])
```

However, it does not, giving a default value of null to a field ('y') without a default value.

This stems from [the use of .get()](https://github.com/tebeka/fastavro/blob/53648c81598f40765ef6bd48923a92255ebcc429/fastavro/writer.py#L241), which returns None if the key is not found. 
The field does not have a default value, so datum.get('default') returns None, which is then used as the default value.

This is just mixing up the lack of a value, with a value of null. Instead, the code should check for the field's existence in the datum, and return false if it doesn't exist.

This is related to #37, in that having write_record call validate() on itself would catch this. Although I imagine the overhead might raise some ire, so there are some options.

Some pull requests will be made in a bit.

**Comment by movermeyer** [comment]
In general, this is a problem with not checking to make sure that the datum contains a value for each field or the field has a default.

In this specific case, it results in data being made up.

**Comment by movermeyer** [comment]
I like @e-heller's solution better. Solves this problem and shouldn't have noticeable impact on performance.

**Comment by tebeka** [comment]
0.9.10 should fix this

**Comment by movermeyer** [comment]
Looks good. Thanks.
