### ISSUE TITLE
High CPU Utilisation

### ISSUE THREAD

**Issue by mohitapplift** [tebeka/fastavro#51]
I am using fastavro for processing live log records. The frequency at which I am ingesting log records is around 1000 records/second. The problem I am facing is high CPU utilization. CPU utilisation is always ranging around 100%. Any suggestion is most welcome

**Comment by tebeka** [comment]
@mohitapplift Can you provide a test case?

**Comment by barrywhart** [comment]
This doesn't seem like a problem per se.  A heavily loaded application will generally max out *some* resource, whether CPU, disk, network, etc.

It sounds like you wish the library was faster.

In the absence of a faster implementation, you might be able to parallelize the processing (e.g. two subprocesses, each processing 500 records/second).

**Comment by scottbelden** [comment]
Agree with @barrywhart. I'm going to close this. If you believe there are bugs that are causing unnecessary computation please create a new issue.
