### ISSUE TITLE
Performance Optimizations: Function calls are taxing

### ISSUE THREAD

**Issue by brianbruggeman** [tebeka/fastavro#58]
Python incurs significant overhead when functions are called.  

Looking at just the writer functionality...

One clear optimization here is not to create functions (e.g. Null/None) when they do nothing.  Another option is to possibly replace functions that are just wrappers (.e.g utf8, long and bytes).  Probably the most performant optimization is to simply use an if block rather than a map with a function call.  You might modify the mapping to identify the struct pack character rather than calling a function.

Based on my quick look at a `cython -a <filename>`, and then opening up the html file, I can see that all of the functions are still using their python form rather than a pure C form.  So one of the worst performance problems of python (function calls) is not being replaced by Cython.  That tells me there's a lot of room for improvement.

The Cython solution is to create a hybrid cython file:  pyx.  And to really focus on creating types and memory allocation.  With enough massaging, it won't look much like python at all (nor will it look like C) but it will be fast.  It also ends up ruining DRY and you'll have to maintain two files.

However, if you have to maintain two files anyway, the better approach is probably to move to C or possibly Python's C-API for the slow pieces.

**Comment by tebeka** [comment]
Thanks for reporting! This is a big task which current I don't have the bandwidth to do. Switching from Cython to C is something I need to think about. There are many other consideration other than speed, and C makes it easy to make a lot of mistakes.

Another option I was considering was wrapping the [Avro C library](https://avro.apache.org/docs/current/api/c/) with Cython.

As always - patches are welcome :)

**Comment by brianbruggeman** [comment]
I looked (a little) into wrapping the Avro C Library.  I think that it's a viable approach.

In wrapping, you still have multiple choices.

libffi -- you get to retain compatibility with pypy at the expense of a long warmup time for cpython and overhead while executing
ctypes -- is more performant for cpython but still has overhead
python c-api -- no compatibility with pypy, but highly performant

For what it's worth, I'm currently looking at a 10 ms window for one of my data sources and in that window, I need to receive the data on a REST API, store it to a local file and then create a response.  I've created a lua plugin for nginx to stay within that window.  But, I'd also like to have a side process which reads my local file and sends it to kafka with the avro encoding.  I'm not necessarily constrained by that 10 ms window, but I do not want to overload the system with avro encoding... so speed is still important.

If you and I cannot agree on an approach here, I'll end up building another avro library for python with python's C-API.  I'd prefer not to stratify the community with a 4th option (avro, fastavro, avro-python, ... my tbd library...).  Given that you're open to patches, where would you fall if I went for the python c-api for fastavro?

**Comment by tebeka** [comment]
Thanks @brianbruggeman. Here are few of my thoughts:

> I looked (a little) into wrapping the Avro C Library. I think that it's a viable approach.

I did look into it when starting fastavro, however at the time it was in alpha state. It might be a good option but we need to think how to make the build complexity small. Currently fastavro has an optional dependency on snappy and I'd like to keep it like that.

> In wrapping, you still have multiple choices.

There are other choices such as SWIG and Cython. I prefer to stay in Cython since it much easier than writing C and less prone to error. A lot of libraries who are performance aware (e.g. pandas) use it with great success.

> For what it's worth, I'm currently looking at a 10 ms window for one of my data sources and in that window, I need to receive the data on a REST API, store it to a local file and then create a response

Did you try with fastavro and it wasn't fast enough? Also from what you're describing it looks like you spend a lot on IO (network and disk). Can you profile?

> If you and I cannot agree on an approach here, I'll end up building another avro library for python with python's C-API. I'd prefer not to stratify the community with a 4th option

I agree. Let's try and make it work. My main goals are to keep the same API and to continue support all the Python versions/distributions we do (see [tox.ini](tox.ini))

**Comment by wesm** [comment]
You all are familiar with https://github.com/Byhiras/pyavroc?

**Comment by tebeka** [comment]
@wesm Thanks, wasn't aware of pyavroc.

**Comment by brianbruggeman** [comment]
@wesm Thank you for the link - that looks promising minus the required patches on avro-c.

**Comment by brianbruggeman** [comment]
@tebeka My proposal is an addition rather than a replacement.

```
try:
    import extension
except ImportError:
    import whatever_was_here
```

**Comment by tebeka** [comment]
@brianbruggeman It's more than that. You'll want the extension built most of the time and you'll need to match the API to `whatever_was_here` which means code duplication and possible errors.

**Comment by brianbruggeman** [comment]
@tebeka As I mentioned above, you will already have code duplication if you explore cython more.  The only mechanism to increase speed is to produce a cython specific file.

**Comment by tebeka** [comment]
@brianbruggeman Currently I try hard to keep one code base. I'd like to see some numbers showing performance improvement before splitting the code.

**Comment by brianbruggeman** [comment]
@tebeka I think it's fair to ask for numbers.  Can you give me a sense of how much you want me to implement to provide proof?  In addition, there's probably other considerations here besides wall-clock:  memory usage and cpu intensity.

These are the variances I see:
- naive python
- cython enhanced (i.e. use cython to build a c-file)
- cython optimized (i.e. build a cython specific file)
- c-library and using ctypes/cffi
- python's C-API

Frankly, there's ample proof on google for solving other problems that show that the above order/sequence is accurate from least performant to most.  But obviously numbers will vary based on problem, and I don't have any base numbers for a solution I've not created.

**Comment by brianbruggeman** [comment]
It appears that someone has already done the work.  

https://github.com/MaxPoint/cyavro/tree/master/cyavro

**Comment by andrusha** [comment]
@brianbruggeman 

* https://github.com/MaxPoint/cyavro looks good, but it is developed for a very particular use-case of writing and reading pandas dataframes, which should be isolated from the avro reader-writer itself, imo.
* https://github.com/Byhiras/pyavroc does require _some_ patches, but from what I see it could be modified to work with upstream avro-c. It probably is a better way to go in order not to re-implement avro format yourself, which could lead to some tricky bugs.

**Comment by brianbruggeman** [comment]
@andrusha I feel like adding system level dependencies and then requiring a patch on top of that makes installation/setup irritating at best and unusable at worse.  I don't think patching libavro makes sense from a deployment perspective or should be a requirement for building a python library.  This is especially true since I don't think that pyavroc's patches branch has been well maintained or kept up-to-date with the upstream.  

My growing list of avro implementations for python now includes.  We (and I mean the community) should find a way to focus efforts on just one.  I feel like fastavro is the best middle-ground right now and the only thing I want more from fastavro is better performance.
* [avro](https://github.com/apache/avro/tree/master/lang/py)  (official python 2)
* [avro-python](https://github.com/apache/avro/tree/master/lang/py3)  (official python 3 - different api than py2 )
* [cyavro](https://github.com/MaxPoint/cyavro)
* [pyavroc](https://github.com/Byhiras/pyavroc)
* [fastavro](https://github.com/tebeka/fastavro)

**Comment by andrusha** [comment]
We could most likely get rid of those patches and just use the upstream, but I got your point. I think the good side of pyavroc is that it doesn't require reimplementation of avro itself, just the interface.

I like fastavro for its simplicity, but then it's not 100% compatible with avro 1.7 and doesn't support 1.8. It looks unnecessary expensive to reimplement standard from scratch.

**Comment by tebeka** [comment]
The major reason that fastavro is falling behind the Avro spec is that I haven't worked with Avro in the last 4 years or so. If anyone wants to to submit patches - they are more than welcomed.

**Comment by andrusha** [comment]
I'm thinking about coding avro 1.8 logical date and time types support.

Why do you guys use Python avro for?

**Comment by brianbruggeman** [comment]
@andrusha I'd be happy to help.  Let me know how.

**Comment by barrywhart** [comment]
I created a [PR](https://github.com/tebeka/fastavro/pull/114) with an updated writer implementation that incorporates many of the ideas mentioned here. I'm interested to hear what you think.

**Comment by scottbelden** [comment]
I think this can be closed now that https://github.com/tebeka/fastavro/pull/114 and https://github.com/tebeka/fastavro/pull/118 have been merged.
