### ISSUE TITLE
Exporting fastavro._writer.Writer

### ISSUE THREAD

**Issue by gmr** [tebeka/fastavro#63]
Great library, thanks for your work.

I've got a use case where I do not want to load all of the records into memory before calling `fastavro.writer()` to write them to a container. Instead, I am creating an instance of `fastavro._writer.Writer` so I can have one writer object and invoke `fastavro._writer.Writer.write` and `fastavro._writer.Writer.flush` myself. 

While this works, it feels dirty accessing your private by convention modules.

Are you open to a PR that would add the `Writer` class to the top-level exports in `fastavro/__init__.py`?

**Comment by tebeka** [comment]
Thanks! Go ahead and submit a PR.
FYI the input to `fastavro.write` is an iterator. Which means you can produce one record at a time when writing them.

**Comment by gmr** [comment]
I ended up using a generator to get around the memory issues I was encountering.
