### ISSUE TITLE
Support for snappy codec

### ISSUE THREAD

**Issue by boompig** [tebeka/fastavro#71]
Stack trace:

```
Traceback (most recent call last):
  File "get_sig_set.py", line 34, in <module>
    records = get_records_fastavro("avro-files/" + fname)
  File "get_sig_set.py", line 11, in get_records_fastavro
    records = [record for record in reader]
  File "fastavro/_reader.py", line 432, in _iter_avro (fastavro/_reader.c:9237)
ValueError: Unrecognized codec: u'snappy'
```

Version: 0.12.2
Python: 2.7.13

**Comment by scottbelden** [comment]
Do you have `python-snappy` installed? `snappy` will only be available as a codec if you have that installed: https://github.com/tebeka/fastavro/blob/master/fastavro/reader.py#L411-L422

What's your current `pip list`?

**Comment by boompig** [comment]
No, I did not. I installed that module and everything worked fine. Please feel free to close.

**Comment by tebeka** [comment]
Thanks @scottbelden !
