### ISSUE TITLE
Allow writer to support lists or tuples (or named tuples) in addition to dict as record type

### ISSUE THREAD

**Issue by brianbruggeman** [tebeka/fastavro#76]
The [writer](https://github.com/tebeka/fastavro/blob/8d304a6084130fd152fd892153327df5e70363b8/fastavro/writer.py#L428-L483) currently requires a dictionary to process each record entry, but the documentation indicates that it's okay to use an iterable, with no requirement imposed on data structure.

```
In [1]: import fastavro

In [2]: schema = {"type": "record", "fields": [{"name": "name", "type": "string"}, {"name": "type", "type": "string"}]}

In [3]: records = [
   ...:     ("apple", "fruit"),
   ...:     ("banana", "fruit"),
   ...: ]

In [4]: path = "tmp.avro"

In [5]: with open(path, 'wb') as stream:
   ...:     fastavro.writer(stream, schema, records)
   ...:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-3c54c57bc598> in <module>()
      1 with open(path, 'wb') as stream:
----> 2     fastavro.writer(stream, schema, records)
      3

<redacted>/site-packages/fastavro/_writer.so in fastavro._writer.writer (fastavro/_writer.c:12273)()

<redacted>/site-packages/fastavro/_writer.so in fastavro._writer.writer (fastavro/_writer.c:12052)()

<redacted>/site-packages/fastavro/_writer.so in fastavro._writer.Writer.write (fastavro/_writer.c:11527)()

<redacted>/site-packages/fastavro/_writer.so in fastavro._writer.write_data (fastavro/_writer.c:8450)()

<redacted>/site-packages/fastavro/_writer.so in fastavro._writer.write_record (fastavro/_writer.c:8310)()

<redacted>/site-packages/fastavro/_writer.so in fastavro._writer.write_record (fastavro/_writer.c:8117)()

ValueError: no value and no default for name

In [6]: records_as_dict = [
   ...:     {'name': 'apple', 'type': 'fruit'},
   ...:     {'name': 'banana', 'type': 'fruit'},
   ...: ]

In [7]: with open(path, 'wb') as stream:
   ...:     fastavro.writer(stream, schema, records_as_dict)
   ...:
```

It would make sense that a tuple, list or namedtuple would be an easy (and possibly preferred) data structure to be used in addition to a dictionary.  This is especially true if the data is already in a column-based format (e.g.  `string.split('\t')`, csv read, db read, etc.).

**Comment by tebeka** [comment]
Thanks for reporting!

I agree it'll be nicer however there a performance penalty when checking type of object, and we need to check how bad it is.

`fastavro` is in low maintenance mode, it might be a while until I get to this. However patches are always welcomed ;)

**Comment by scottbelden** [comment]
@brianbruggeman I think you might be reading the documentation wrong (or maybe it should be clearer). I'm assuming you are referring to this section:

```
# 'records' can be any iterable (including a generator)
records = [
    {u'station': u'011990-99999', u'temp': 0, u'time': 1433269388},
    {u'station': u'011990-99999', u'temp': 22, u'time': 1433270389},
    {u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
    {u'station': u'012650-99999', u'temp': 111, u'time': 1433275478},
]
```

The iterable it is referring to is the structure holding the dictionaries. So for example, instead of a list, it could be a tuple, generator, etc.

**Comment by brianbruggeman** [comment]
@scottbelden I'm aware (that should be explicitly noted by the example I posted above).  

My thought is that if you already have a data structure that is basically in a row format (i.e. a list or tuple), you shouldn't be required to convert to a mapped structure (dict) only to have it be converted right back.  That's a penalty that shouldn't be incurred, especially when the data itself is already basically ready for writing (provided it does meet a few conditions... e.g. shape/size).

**Comment by scottbelden** [comment]
How would you deal with the scenario of default values? In your example where a schema has a `name` and `type` field, suppose the name has a default value of `fruit_name` and the type has a default value of `fruit_type`. If I gave it the "record" `("apple",)`, would it be serialized as

```
name: apple
type: fruit_type
```
or
```
name: fruit_name
type: apple
```

**Comment by brianbruggeman** [comment]
I only see two viable options:

*  1.  Naive: the record is not the appropriate length.
*  2.  Stupid:  the record can postpend default values.  i.e. it would handle your example above but it wouldn't work for inserts

I think that if the record length does not explicitly match, then the output shouldn't be written and an exception should be raised indicating a mismatch between schema and record.

I think the Naive approach is probably "smarter" as it explicitly avoids attempting to be smart in any way.  And I can think of a scenario where someone might want to interleave default values.  What I think should be avoided is any attempt to put data in the wrong spot.  

Arguable, your example above can be solved pretty easily (and I did write some code up already to do that...).  But I'm not sure it really makes sense for this to be too smart.

**Comment by ngeraedts** [comment]
I would recommend against implementing this kind of behaviour. In your first example, you've specified a record (i.e. a python dictionary, or a JSON object) and provided tuples. The data types don't match - it even doesn't match via duck-typing.

I've seen many other libraries try to do the "smart" thing and adjust data types to match desired behaviour. This often leads to situations where you expect an operation to fail, but it doesn't because the library's internals mask some underlying issue for you.

We've chosen to use Avro (and `fastavro` as the implementation library) for our internal data formats precisely because it doesn't make any assumptions. Either the data provided matches the schema exactly or it doesn't and you get an appropriate exception raised.

The following simple test should always hold IMO (with `schema` and `records` being appropriately compatible):

```
import fastavro

with open("data.avro", 'wb') as fh:
    fastavro.writer(fh, schema, records)

with open("data.avro", 'rb') as fh:
    reader = fastavro.reader(fh)
    records_from_file = [datum for datum in reader]

assert records == records_from_file
```

PEP20 #2 - Explicit is better than implicit.

**Comment by scottbelden** [comment]
I agree that this would probably not be a good idea and am going to close the issue.
