### ISSUE TITLE
Add support for aliases

### ISSUE THREAD

**Issue by regisb** [tebeka/fastavro#87]
Currently, fastavro does not support Avro aliases: http://avro.apache.org/docs/current/spec.html#Aliases

Aliases are required for renaming fields, which is a frequent type of schema evolution. At read time, when a field is absent from the writer schema, the field name is looked up among the field aliases.

If you agree this is a feature worth having, I can start working on a PR.

EDIT: simplified the description of this issue to reduce the scope of aliases.

**Comment by yiga2** [comment]
I second this request - useful if one maintains technical & "business" field names. It is not clear to me if **doc** attribute is supported at field-level either. 
If not, @regisb I like to piggyback on your PR as adding support for both attributes would be in the same place.

**Comment by regisb** [comment]
@yiga2 I'm happy to see some interest in this feature! I'm going to be too busy to work on it in the next couple weeks, but I should be able to open a PR before the end of the year. I'm not sure if `doc` is already supported; if not, I will add it to the PR.

**Comment by scottbelden** [comment]
Feel free to submit a PR. Thanks!

**Comment by regisb** [comment]
@yiga2 I just opened a PR to implement aliases, but I did not work on `doc` attributes. It seems to me that they are supported. Which use case did you have in mind?

**Comment by yiga2** [comment]
To store more descriptive information about the record (table) and
column/field. Aliases are useful as well to have a technical and business
name for a field but have a long text to explain further (=doc attribute)
is even better as we are dealing with many flavors of the same data,
depending on the customer. Maintaining a separate data dictionary would be
unnecessary.

I appreciate you reaching out but I will give spavro a try or even avsc.
The latter is for node.js but is superfast, which is critical in my use
case: encoding of 2GB csv files in less than 5min as I want to use
serverless functions (AWS Lambda or G/Az Functions).

Thanks anyways.

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/113
