### ISSUE TITLE
Does fastavro support encoding/decoding without schema?

### ISSUE THREAD

**Issue by johnjang** [tebeka/fastavro#94]
Is it possible to decode/encode messages without having schema in the message itself? My use case is a lot of small messages, and the schema itself is almost always bigger than the data itself.
I wanted something like apache-avro where I don't have to encode schema in the messae itself and hopefully use something like schema-registry in long term.

**Comment by scottbelden** [comment]
You should check out the `schemaless_writer` (https://github.com/tebeka/fastavro/blob/master/fastavro/writer.py#L589) and `schemaless_reader` (https://github.com/tebeka/fastavro/blob/master/fastavro/reader.py#L569) to see if they are what you are looking for.

**Comment by kkirsanov** [comment]
@johnjang 
Example - https://github.com/tebeka/fastavro/blob/master/tests/test_complex.py
