### ISSUE TITLE
logicalType date conversion is incorrect

### ISSUE THREAD

**Issue by bitzstein** [tebeka/fastavro#96]
The Avro 1.8.2 spec (https://avro.apache.org/docs/1.8.2/spec.html#Date) says that the `date` logicalType should be `int stores the number of days from the unix epoch, 1 January 1970 (ISO calendar)`.

The current fastavro code uses `return data.toordinal()` which is the number of days since 0 January 0001, i.e.
```
>>> datetime.date(1,1,1).toordinal()
1
>>> datetime.date(1970,1,1).toordinal()
719163
>>> datetime.date(2017,9,8).toordinal()
736580
```

A more appropriate conversion would be `return (data - datetime.date(1970,1,1)).days`:
```
>>> (datetime.date(1,1,1) - datetime.date(1970,1,1)).days
-719162
>>> (datetime.date(1970,1,1) - datetime.date(1970,1,1)).days
0
>>> (datetime.date(2017,9,8) - datetime.date(1970,1,1)).days
17417
```

Alternatively, `return data.toordinal() - 719163` would probably be the fastest.

**Comment by kkirsanov** [comment]
Thanks for the bug.

I will fix it in the near future.

**Comment by kkirsanov** [comment]
For now you can use this code to monkey-patch

```
import fastavro

def read_date(data, writer_schema=None, reader_schema=None):
    return datetime.date.fromordinal(data+719163)

def prepare_date(data, schema):
    return data.toordinal() - 719163

fastavro._writer.LOGICAL_WRITERS['int-date']=prepare_date
fastavro._reader.LOGICAL_READERS['int-date']=read_date
```
