### ISSUE TITLE
Support for time logicalTypes

### ISSUE THREAD

**Issue by bitzstein** [tebeka/fastavro#97]
As per the Avro 1.8.2 spec (https://avro.apache.org/docs/1.8.2/spec.html#Date), there are a number of date/time related logicalTypes, which are serialized as int or long.

Currently fastavro supports conversions between:
- `datetime.date` and logicalType `date`
- `datetime.datetime` and logicalTypes `timestamp-millis`, `timestamp-micros`

I'd like support added for conversions between:
- `datetime.time` and logicalTypes `time-millis`, `time-micros`

This seems pretty straightforward:
```
>>> t = datetime.time(13, 25, 9, 723743)
>>> int(t.hour * 3600000 + t.minute*60000 + t.second*1000 + t.microsecond/1000)
48309723
>>> t.hour * 3600000000 + t.minute*60000000 + t.second*1000000 + t.microsecond
48309723743
```

**Comment by kkirsanov** [comment]
Done - https://github.com/tebeka/fastavro/pull/98

Waiting for approve :)
